---
name: Test

on:
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  
  test-repository:
    name: Tests Repository.UnitTests
    uses: Red-Papers-Studio/.github/.github/workflows/dotnet_test.yml@main
    with:
      dotnet_version: 6.0.x
      project_name: Repository.UnitTests
      test_path: Repository/Repository.UnitTests
  
  test-modifiable-entities:
    name: Tests ModifiableEntities.UnitTests
    uses: Red-Papers-Studio/.github/.github/workflows/dotnet_test.yml@main
    with:
      dotnet_version: 6.0.x
      project_name: ModifiableEntities.UnitTests
      test_path: ModifiableEntities/ModifiableEntities.UnitTests 
      
  test-domain-driven-design:
    name: Tests DomainDrivenDesign.UnitTests
    uses: Red-Papers-Studio/.github/.github/workflows/dotnet_test.yml@main
    with:
      dotnet_version: 6.0.x
      project_name: DomainDrivenDesign.UnitTests
      test_path: DomainDrivenDesign/DomainDrivenDesign.UnitTests
